### PR TITLE
Update PHP to 8.2 and enable zlib

### PR DESCRIPTION
**Pull request by pjcdawkins**
#54 

Check various needed extensions are installed ... I've checked for linux/amd64:

- [x] curl
- [x] json
- [x] openssl
- [x] pcre
- [x] phar

plus desirable extensions:

- [x] zlib (for using gzip over HTTP)
- [x] pcntl and posix (for enabling the `tunnel:open` command)

### CODE REVIEW

**Review by akalipetis — CHANGES_REQUESTED** [review]
We should remove deprecation warning before bumping the PHP version.

I get the following ones when logging in:

```console

Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /home/akalipetis/.platformsh/oauth-listener/index.php on line 45

Warning: Cannot modify header information - headers already sent by (output started at /home/akalipetis/.platformsh/oauth-listener/index.php:45) in /home/akalipetis/.platformsh/oauth-listener/index.php on line 187

Warning: Cannot modify header information - headers already sent by (output started at /home/akalipetis/.platformsh/oauth-listener/index.php:45) in /home/akalipetis/.platformsh/oauth-listener/index.php on line 187

Warning: Cannot modify header information - headers already sent by (output started at /home/akalipetis/.platformsh/oauth-listener/index.php:45) in /home/akalipetis/.platformsh/oauth-listener/index.php on line 187
```

**Comment by pjcdawkins** [comment]
> We should remove deprecation warning before bumping the PHP version.

Things that stop it working, yes. There are definitely deprecations, which are unavoidable as it still supports PHP 5.6+ and various libraries include deprecated code (mostly Guzzle). They're usually hidden unless you define `PLATFORMSH_CLI_REPORT_DEPRECATIONS=1` as an env var and run with `-vvv`.

**Comment by pjcdawkins** [comment]
Rebased

**Comment by pjcdawkins** [comment]
Rebased again / updated to [8.2.10](https://www.php.net/ChangeLog-8.php)

**Comment by pjcdawkins** [comment]
```
$ ./internal/legacy/archives/php_linux_amd64 --version

PHP 8.2.10 (cli) (built: Sep 20 2023 16:58:29) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.10, Copyright (c) Zend Technologies

$ ./internal/legacy/archives/php_linux_amd64 -r 'foreach (["curl", "json", "openssl", "pcre", "phar", "zlib", "posix", "pcntl"] as $ext) echo extension_loaded($ext) ? "$ext: found\n" : "$ext: not found :(\n";'

curl: found
json: found
openssl: found
pcre: found
phar: found
zlib: not found :(
posix: found
pcntl: found
```

**Comment by pjcdawkins** [comment]
Rebased + updated to [8.2.11](https://www.php.net/ChangeLog-8.php)

**Comment by pjcdawkins** [comment]
I've added zlib

I haven't tested if this builds OK for Windows / OS X / ARM

**Review by akalipetis — APPROVED** [review]
LGTM 🐻

**Comment by akalipetis** [comment]
Deprecation warnings are gone and everything seems to be working great!

**Pull request merged**
